databases:
  - name: minori_tsunagaru
    databaseName: minori_tsunagaru
    user: riri
    region: Oregon

services:
  - type: web
    name: minori_tsunagaru
    env: ruby
    region: Oregon
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    preDeployCommand: |
      ./bin/rails db:migrate
      ./bin/rails db:seed
                     
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: minori_tsunagaru
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 2